<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AbstractPhrictionPage' => 'domain/AbstractPhrictionPage.php',
    'ConverterService' => 'service/ConverterService.php',
    'ImportMediaWikiWorkflow' => 'workflow/ImportMediaWikiWorkflow.php',
    'ImportMediaWikiWorkflowCategoriesWorkflow' => 'workflow/ImportMediaWikiWorkflowCategoriesWorkflow.php',
    'ImportMediaWikiWorkflowPagesWorkflow' => 'workflow/ImportMediaWikiWorkflowPagesWorkflow.php',
    'MediaWikiService' => 'service/MediaWikiService.php',
    'PhrictionImage' => 'domain/PhrictionImage.php',
    'PhrictionCategory' => 'domain/PhrictionCategory.php',
    'PhrictionPage' => 'domain/PhrictionPage.php',
    'PhrictionService' => 'service/PhrictionService.php',
    'ScriptingUtils' => 'utils/ScriptingUtils.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AbstractPhrictionPage' => 'Phobject',
    'ConverterService' => 'Phobject',
    'ImportMediaWikiWorkflow' => 'PhutilArgumentWorkflow',
    'ImportMediaWikiWorkflowCategoriesWorkflow' => 'ImportMediaWikiWorkflow',
    'ImportMediaWikiWorkflowPagesWorkflow' => 'ImportMediaWikiWorkflow',
    'MediaWikiService' => 'Phobject',
    'PhrictionImage' => 'Phobject',
    'PhrictionCategory' => 'AbstractPhrictionPage',
    'PhrictionPage' => 'AbstractPhrictionPage',
    'PhrictionService' => 'Phobject',
    'ScriptingUtils' => 'Phobject',
  ),
));
